---
     minecraft_version: "1.19.3" #need to find a way to use correctly
     minecraft_jar_path: "/home/minecraft/minecraft_server.jar"
     minecraft_tmp_jar_path: "/home/minecraft/minecraft_server.tmp"
     minecraft_min_ram: "2"
     minecraft_max_ram: "4"
     minecraft_cron_path: "/home/minecraft/minecraft.crontab"
     minecraft_port: "25565"
