---
  - name: dependency repos
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items: "{{ non_free_repos }}"

  - name: dpkg 32bit arch
    command: dpkg --add-architecture i386

  - name: steamcmd debconf seen
    debconf:
      name: "steamcmd"
      question: "steam/license"
      vtype: "seen"
      value: "true"

  - name: steamcmd debconf selection
    debconf:
      name: "steamcmd"
      question: "steam/question"
      value: "I AGREE"
      vtype: "select"

  - name: packages
    apt:
      pkg:
      - software-properties-common
      - lib32gcc-s1
      - steamcmd
      state: latest
      update_cache: yes

  - name: steam group
    group:
      name: steam
      state: present

  - name: steam user
    user:
      name: steam
      group: steam
      create_home: true
      shell: /bin/bash

  - name: download valheim
    command: /usr/games/steamcmd +login anonymous +app_update 896660 +quit
    become: yes
    become_user: steam

  - name: for steamclient library
    file:
      path: /home/steam/.steam/sdk64
      state: directory
      mode: '0755'

  - name: create a symbolic link for steamclient library
    file:
      src: "/home/steam/Steam/steamapps/common/Valheim dedicated server/linux64/steamclient.so"
      dest: /home/steam/.steam/sdk64/steamclient.so
      owner: steam
      group: steam
      state: link

  - name: valheim start script
    template:
      src: templates/start_script.sh.j2
      dest: /home/steam/Steam/steamapps/common/Valheim dedicated server/start_script.sh
      owner: steam
      group: steam
      mode: '0700'

  - name: valheim service file
    template:
      src: templates/valheim.service.j2
      dest: /etc/systemd/system/valheim.service
      owner: root
      group: root

  - name: valheim service
    systemd:
     name: valheim
     state: started
     enabled: true
     daemon_reload: true

  - name: valheim ports
    ufw:
      rule: allow
      to_port: "{{ item }}"
      proto: "udp"
    with_items: "{{ valheim_ports }}"

