---
   - name: wait for dpkg lock
     shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

   - name: wait for apt lock
     shell: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 5; done;

   - name: packages
     apt:
       pkg: 
       - sudo
       - vim 
       - ufw  
       - fail2ban
       state: present
       state: latest
       update_cache: yes

   - name: ufw allow ssh
     ufw:
       rule: allow
       name: OpenSSH

   - name: ufw default deny
     ufw:
       default: deny
       state: enabled

   - name: fail2ban ssh jail
     template:
       src: templates/fail2ban.ssh.conf.j2
       dest: /etc/fail2ban/jail.d/sshd.conf

   - name: sshd no passwd auth
     template:
       src: templates/sshd_config.override.j2
       dest: /etc/ssh/sshd_config.d/override.conf
     notify:
       - restart sshd
   
   - name: fail2ban service
     systemd:
       name: fail2ban
       state: started
       enabled: true
