---
  - name: install prom snmp exporter
    apt:
      pkg: 
        - prometheus-snmp-exporter
        - unzip 
        - build-essential 
        - libsnmp-dev
        - git
        - golang

  - name: snmp generator download
    git:
      repo: https://github.com/prometheus/snmp_exporter.git
      dest: /home/prometheus/snmp_exporter
    register: git
      
  - name: make mibs
    shell: "make generator mibs"
    args:
      chdir: /home/prometheus/snmp_exporter
    when: git.changed is true
    register: make
  
  - name: snmp exporter config
    template:
      src: templates/snmp.yml.j2
      dest: /etc/prometheus/snmp.yml.managed
      owner: prometheus
      group: prometheus
      mode: '0644'
    
  - name: start snmp exporter and enable
    systemd:
      name: snmp-exporter
      enabled: true