---
  - name: install prom snmp exporter
    apt:
      pkg: 
        - prometheus-snmp-exporter
        - unzip 
        - build-essential 
        - libsnmp-dev
        - git
  
  - name: golang install for snmp generator

  - name: snmp generator download
    git:
      repo: https://github.com/prometheus/snmp_exporter.git
      dest: /home/prometheus/snmp_exporter
    register: git
      
  - name: generator.yml template
      
  - name: make mibs
    shell: "make generator mibs"
    args:
      chdir: /home/prometheus/snmp_exporter/generator
    when: git.changed is true
    register: make
  
  - name: copy generated config to running server

  - name: start snmp exporter and enable
    systemd:
      name: prometheus-snmp-exporter
      enabled: true