---
  - name: prometheus packages
    apt:
      pkgs:
        - prometheus
        
  - name: prometheus config template
    template:
      src: templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
      mode: '0644'
 
  - name: prometheus server start/enable
    systemd:
      state: started
      enabled: true
      name: prometheus